apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluedep
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      apps: jio
  template:
    metadata:
      labels:
        apps: jio
    spec:
      containers:
        - name: ngin
          image: nginx:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-svc
spec:
  type: NodePort
  selector:
    apps: jio
  ports:
    - targetPort: 80
      port: 8080
      nodePort: 31127
