apiVersion: v1
kind: ReplicationController
metadata:
  name: demo
spec:
  replicas: 3
  selector:
    app: meta  
  template:
    metadata:
      labels:
        app: meta
    spec:
      containers:
        - name: healm
          image: nginx:latest
          ports:
            - containerPort: 80
